name: better_polls
description: A better flutter widget for polls, this immitates the twitter polls system, all you need do is connect you data to the polls, it allows voting and visualization.
version: 1.0.0
homepage: https://github.com/tjcampanella/better_polls

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.2
  collection: ^1.15.0

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter
